require "user.options"
require "user.keymaps"
require "user.vim-compat" -- 迁移自 .vimrc 的兼容配置
require "user.plugins"
require "user.colorscheme"
require "user.transparency"
require "user.cmp"
require "user.lsp"
require "user.telescope"
-- require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.lsp.settings.rust_ls"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.todo-comments"
